[package]
name = "check"
version = "0.1.0"
edition = "2021"


[[bin]]
name="ck"
path="src/main.rs"


[dependencies]
rayon = {version = "1.10.0"}
clap = {version = "4.5.7",features = ["default","derive"]}
walkdir = {version = "2.5.0"}
md-5 = "0.11.0-pre.3"
hex = "0.4.3"
prettytable = "0.10.0"
